# Generated by Django 4.0.6 on 2022-08-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureslider',
            old_name='difficulty',
            new_name='ps_difficulty',
        ),
        migrations.RenameField(
            model_name='pictureslider',
            old_name='image_url',
            new_name='ps_image_url',
        ),
        migrations.RenameField(
            model_name='pictureslider',
            old_name='moves',
            new_name='ps_moves',
        ),
        migrations.RenameField(
            model_name='tileflip',
            old_name='difficulty',
            new_name='tf_difficulty',
        ),
        migrations.RenameField(
            model_name='tileflip',
            old_name='moves',
            new_name='tf_moves',
        ),
    ]
