# Generated by Django 4.0.6 on 2022-08-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureslider',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usersavedata',
            name='image_slider_img',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
