# Generated by Django 4.0.6 on 2022-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0002_alter_pictureslider_moves_alter_riddle_riddle_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureslider',
            name='difficulty',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tileflip',
            name='difficulty',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='usersavedata',
            name='image_slider_difficulty',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='usersavedata',
            name='image_slider_orientation',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='usersavedata',
            name='riddle_letter_choices',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='usersavedata',
            name='tile_flip_difficulty',
            field=models.CharField(max_length=250),
        ),
    ]
