# Generated by Django 4.0.6 on 2022-08-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0003_alter_pictureslider_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedata',
            name='image_slider_started',
            field=models.BooleanField(default=False),
        ),
    ]
